### ISSUE TITLE
Feature: Enable worker to create a job

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#12]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Worker should be able to create a job from when the manager instructs it. By default we can start the job once it has been created. 

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Why should Worker, i.e Proplet, create a job? It will just receive instruction (command) to start a binary.

**Comment by drasko** [comment]
Will be implemented in https://github.com/absmach/propeller/issues/26 if needed
