### ISSUE TITLE
Feature: Enable worker to fetch job

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#14]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

A worker should be able to fetch a job. The job can either live in memory or on an embeddable key-value store.

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Will be implemented in https://github.com/absmach/propeller/issues/26 if needed
