### ISSUE TITLE
Feature: Enable worker to delete a job

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#16]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Worker should be able to delete a job. This should be synchronised with the manager i.e. once the manager has deleted the job the worker should delete it. Consider handling edge cases. For example, when the job fails to be deleted on the worker it has been deleted on the manager.

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Why should Proplet know what the Job is? It shouldjust receive a batch of tasks and execute them. In any case this functionality should be implemented in other issues describing Manager and Proplet services.
