### ISSUE TITLE
Feature: Implement Job Functionality

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#2]
### Is your feature request related to a problem? Please describe.

Currently, we are only able to run a single jobs which is not ideal for production use cases since workflows are sometimes nested

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Implement Job functionality so that we can run multiple tasks as one job

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
I am not sure about this. We will use Propeller for deploying simple Wasm modules, not complex jobs. Let's put this one low priority for now.

**Comment by drasko** [comment]
Will be handled in https://github.com/absmach/propeller/issues/25
