### ISSUE TITLE
Feature: Enable Manager to communicate with worker using supermq

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#20]
### Is your feature request related to a problem? Please describe.

No

### Describe the feature you are requesting, as well as the possible use case(s) for it.

The manager should be able to communicate with workers to be able to send jobs and receive results from them. This will be enabled by using SuperMQ under the hood.

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
This should not be a separate issue - it is Manager service.
