### ISSUE TITLE
Feature: Represent Job as Universal Format

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#3]
### Is your feature request related to a problem? Please describe.

We don't have a way to represent jobs

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Represent jobs in a universal format for example JSON so that jobs can be created with multiple tasks using API

### Indicate the importance of this feature to you.

Must-have

**Comment by drasko** [comment]
Will be handled in https://github.com/absmach/propeller/issues/25
