### ISSUE TITLE
Feature: Allocate Magistrala Resources

### ISSUE THREAD

**Issue by rodneyosodo** [absmach/propeller#4]
### Is your feature request related to a problem? Please describe.

There is no communication in between jobs

### Describe the feature you are requesting, as well as the possible use case(s) for it.

Setup Magistrala things and channels for communication in between jobs

### Indicate the importance of this feature to you.

Must-have

### Anything else?

Possibility of using embedded nats

**Comment by drasko** [comment]
Duplicate of https://github.com/absmach/propeller/issues/8
